# Generated by Django 3.1.13 on 2021-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_actors_transactioncategory_transactions_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
